apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: nginx-namespace
spec:
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2", "--timeout", "300s"] # 2 CPUs for 5 minutes
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
