name: Deploy to Kubernetes on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Kubectl on Windows
      run: |
        curl -LO "https://dl.k8s.io/release/v1.27.0/bin/windows/amd64/kubectl.exe"
        mkdir -Force C:\kubectl
        Move-Item -Path .\kubectl.exe -Destination C:\kubectl\
        [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';C:\kubectl', [System.EnvironmentVariableTarget]::Machine)
        kubectl version --client

    - name: Configure Kubeconfig on Windows
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        $decodedConfig = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:KUBE_CONFIG_DATA))
        mkdir -Force $HOME\.kube
        Set-Content -Path "$HOME\.kube\config" -Value $decodedConfig
        kubectl config view

    - name: Verify Cluster Connectivity
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Create Namespace
      run: |
        kubectl create namespace nginx-namespace || echo "Namespace already exists"

    - name: Deploy Nginx Deployment
      run: |
        kubectl apply -f deployment/nginx-deployment.yaml --namespace nginx-namespace
        kubectl apply -f deployment/nginx-service.yaml --namespace nginx-namespace

    - name: Deploy KEDA ScaledObject
      run: |
        kubectl apply -f deployment/keda-scaledobject.yaml --namespace nginx-namespace

    - name: Verify Deployment
      run: |
        kubectl get all -n nginx-namespace
        kubectl describe pods -n nginx-namespace
